replicaCount: 1

image:
  repository: ghost
  tag: "6.5"
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    helm.sh/resource-policy: keep
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-Host  $host;
      proxy_set_header Host              $host;

  hosts:
    - host: blog.atarnet.org
      path: /
  tls: []

persistence:
  enabled: true
  existingClaim: ""
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  url: https://blog.atarnet.org
  database__client: sqlite3
  database__connection__filename: /var/lib/ghost/content/data/ghost.db
  trustProxy: "true"

extraEnv: []

extraEnvFrom: []

extraVolumeMounts: []

extraVolumes: []
